use_frameworks!

platform :ios, '14.0'

target 'Sandbox' do
  project 'Sandbox.xcodeproj'
  # Dev mode
  pod 'Reach5Future', :path => '../Reach5Future.podspec'
  pod 'Reach5', :path => '../../reachfive-ios/Reach5.podspec'
#   pod 'Reach5Google', :path => '../../reachfive-ios-google/Reach5Google.podspec'
#   pod 'Reach5Facebook', :path => '../../reachfive-ios-facebook/Reach5Facebook.podspec'
  # pod 'Reach5WeChat', :path => '../../reachfive-ios-wechat/Reach5WeChat.podspec'

end
