use_frameworks!

platform :ios, '14.0'

target 'Sandbox' do
  project 'Sandbox.xcodeproj'
  # Dev mode
  pod 'IdentitySdkCore', :path => '../IdentitySdkCore.podspec'
  pod 'IdentitySdkGoogle', :path => '../../reachfive-ios-google/IdentitySdkGoogle.podspec'
  # pod 'IdentitySdkFacebook', :path => '../IdentitySdkFacebook.podspec'
  # pod 'IdentitySdkWeChat', :path => '../IdentitySdkWeChat.podspec'

end
