# iOS CircleCI 2.0 configuration file
# https://circleci.com/docs/configuration-reference/
#
# For XCode build version available
# https://circleci.com/docs/using-macos/
#
version: 2.1
jobs:
  build:
    macos:
      xcode: "15.3.0"
    steps:
      - checkout
      - run:
          name: Install CocoaPods
          command: gem install cocoapods --user-install
      - run:
          name: Check Reach5
          command: |
            cd Sources
            pod install
            cd ../
            pod lib lint Reach5.podspec
  build-for-release:
    macos:
      xcode: "15.3.0"
    steps:
      - checkout
      - run:
          name: Install CocoaPods
          command: gem install cocoapods --user-install
      - run:
          name: Check Reach5
          command: |
            cd Sources
            pod install
            cd ../
            pod spec lint Reach5.podspec
  publish:
    macos:
      xcode: "15.3.0"
    steps:
      - checkout
      - run:
          name: Install CocoaPods
          command: gem install cocoapods --user-install
      - run: pod trunk push Reach5.podspec
  build-sandbox:
    macos:
      xcode: "15.3.0"
    working_directory: ~/repo/Sandbox
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Install CocoaPods
          command: gem install cocoapods --user-install
      - run: pod install
      - run: fastlane scan

default_workflows_filters: &default_workflows_filters
  filters:
    tags:
      only: /.*/
    branches:
      ignore: /.*/

default_workflows_tags: &default_workflows_tags
  filters:
    tags:
      only: /.*/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          <<: *default_workflows_tags
      - build-for-release:
          <<: *default_workflows_filters
      - publish:
          requires:
            - build-for-release
          <<: *default_workflows_filters
