= loginWithPassword

[.expand]
icon:warning[] Breaking changes for `8.0.0`, please read.

[.expand-content]
====
[discrete]
include::partial$announcements/800-breaking-changes.adoc[leveloffset=+1]
====

[.signature]
[subs="normal"]
----
AppDelegate.reachfive().loginWithPassword(
    <<email>>,
    <<phoneNumber>>
    <<customIdentifier>>
    <<password>>,
    // Optional arguments
    <<scope>>
)
----

== Description

Authenticate the user with the specified identifier (email, phone number, or custom identifier) and password.
A user may identify themselves with either their email address or their phone number if the SMS feature is enabled.

In the case where step-up authentication is required, `{docname}` returns <<Response, an `OngoingStepUp` response>>.

== Examples

[tabs]
====
With an email icon:envelope-o[]::
+
--
[source, swift]
----
include::example${docname}WithEmail.swift[]
----
--
With a phone number icon:phone-square[]::
+
--
[source, swift]
----
include::example${docname}WithPhoneNumber.swift[]
----
--
With a custom identifier::
+
--
[source,swift]
----
include::example${docname}WithCustomIdentifier.swift[]
----
--
====

== Parameters

[cols="3,7a"]
|===
|Parameter |Description

include::partial$params.adoc[tag="email"]
include::partial$params.adoc[tag="phoneNumber"]
include::partial$params.adoc[tag="customIdentifier"]
include::partial$params.adoc[tag="password"]
include::partial$params.adoc[tag="scope"]

|===

== Response

Type: `Future<LoginFlow.<<AchievedLogin>> | <<OngoingStepUp>>, <<ReachFiveError>>>`

If the credentials are valid, the promise returns the profile's authentication token or continues the step-up process depending on the flow. 
Otherwise it is rejected and returns a `ReachFiveError`.

include::partial$models.adoc[tag=AchievedLogin]

include::partial$models.adoc[tag=OngoingStepUp]

include::partial$models.adoc[tag=reachfiveerror]
