= providerCreator

`{docname}` is a protocol that defines specific social login providers (e.g., Google, Facebook, Apple) available in our {page-component-title}. 
These specific providers use native calls or external libraries to authenticate users.

All providers except xref:docs:ROOT:apple.adoc[Apple] that you configure in the {cc} for which you don't use a specific provider creator will authenticate through an `ASWebAuthenticationSession`.

You should define and configure these providers when you xref:index.adoc#configuration-5[configure the iOS SDK].

== Examples

[source,swift]
----
include::example${docname}.swift[]
----

== Available provider creators

The providers who have a variant parameter have the following algorithm to choose a variant configured on the console.

* icon:check[] If a variant is provided, the variant with the exact name, irrespective of case, is chosen. 
If no variant matches, the algorithm chooses the variant as if no variant was provided.
* [.red]#icon:close[]#  If no variant is provided, the first variant containing `ios` in its name, irrespective of case, if any, is chosen. 
Otherwise, the default variant is chosen.

[cols="3m,7a"]
|===
|Name |Description

include::partial$config/params.adoc[tags="GoogleProvider,FacebookProvider,AppleProvider,WeChat"]

|===
