// tag::GoogleProvider[]
|[[GoogleProvider,GoogleProvider]]GoogleProvider
|The object for configuring xref:index.adoc#google-native-provider[Google native provider] for our {page-component-title}.

Optionally takes a variant parameter.

[source,swift]
----
GoogleProvider(variant: "native") <1>
----
<1> Available from `Reach5Google` 7.1.0.

// end::GoogleProvider[]

// tag::FacebookProvider[]
|[[FacebookProvider,FacebookProvider]]FacebookProvider
|The object for configuring xref:index.adoc#facebook-native-provider[Facebook native provider] for our {page-component-title}.

This provider takes two optional parameters:

* variant `string`: the provider variant to use.
* prefersLoginTracking `FBSDKLoginKit.LoginTracking`: Indicates preference to the Facebook SDK for the limited or classic login. 
Facebook SDK is ultimately responsible for the decision.

[source,swift]
----
FacebookProvider(
    variant: "ios", <1>
    prefersLoginTracking: .limited <2>
)
----
<1> Available from `Reach5Facebook` 7.1.0.
<2> Available from `Reach5Facebook` 7.2.0.

// end::FacebookProvider[]

// tag::AppleProvider[]
|[[AppleProvider,AppleProvider]]AppleProvider
|Optionally takes a variant parameter.

NOTE: Not specifying `AppleProvider` at all in the `providerCreators` array is equivalent to specifying `AppleProvider` with no variant.

[source,swift]
----
AppleProvider(variant: "native") <1>
----
<1> Available from `{company}` 7.1.3.

// end::AppleProvider[]

// tag::WeChat[]
|[[WeChat,WeChat]]WeChat
|The object for configuring xref:index.adoc#wechat-connect[WeChat Connect] for our iOS SDK.

[source,swift]
----
WeChat() <1>
----
<1> WeChat takes no parameters.

// end::WeChat[]
