= Initialize iOS SDK

You must initialize the iOS SDK to use it.
Initializing the iOS SDK ensures the client configuration is properly fetched (which contains default scope) and native social providers are properly initialized.

You initialize your iOS client with:

[source,swift]
----
reachfive.application(application, didFinishLaunchingWithOptions: launchOptions)
----

== Full examples

The full file examples below show you were to initialize the client as well as providing context for the overall configuration and initialization.

[tabs]
====
Minimum configuration::
+
--
[source, swift]
----
import UIKit <1>
import Reach5

class AppDelegate: UIResponder, UIApplicationDelegate {
    let DOMAIN    = "Here paste your ReachFive domain" <2>
    let CLIENT_ID = "Here paste your ReachFive client ID" <3>

    let reachfive = ReachFive(
        // The configuration parameters required to initialize the ReachFive client
        sdkConfig: SdkConfig(domain: DOMAIN, clientId: CLIENT_ID)
    )

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Initialize the ReachFive client
        return reachfive.application(application, didFinishLaunchingWithOptions: launchOptions) <4>
    }
}
----
<1> Import the UIKit if using it.
If using another UI framework, you may not initialize provider configuration.
<2> Your {company} domain such as `integ-sandbox.reach5.dev`.
<3> The {company} client such as `zhU43...51nvOM`;
<4> Initializes the iOS SDK by fetching information from the server about the client.
For more details, see xref:application/applicationDidFinishLaunchingWithOptions.adoc[].

--
Full configuration::
+
--
[source,swift,subs="normal,callouts"]
----
import UIKit
import Reach5
import Reach5Facebook
import Reach5Google
import Reach5WeChat

class AppDelegate: UIResponder, UIApplicationDelegate {
    let DOMAIN    = "Here paste your ReachFive domain" // e.g. integ-sandbox-squad2.reach5.dev
    let CLIENT_ID = "Here paste your ReachFive client ID" // e.g. zhU43aRKZtzps551nvOM

    let reachfive = ReachFive(
        // The configuration parameters required to initialize the ReachFive client
        sdkConfig: SdkConfig(domain: DOMAIN, clientId: CLIENT_ID),
        // The list of the social providers needed by the application
        providersCreators: [GoogleProvider(), FacebookProvider(), WeChatProvider()]
    )

    // Return the ReachFive client
    static func reachfive() -> ReachFive { <1>
        let app = UIApplication.shared.delegate as! AppDelegate
        return app.reachfive
    }

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool { <2>
        reachfive.addPasswordlessCallback { result in
            // Check result and extract the authToken if the callback was successful, then continue your flow (for example redirect to the profile page)
        }

        // Initialize the ReachFive client
        return reachfive.application(application, didFinishLaunchingWithOptions: launchOptions)
    }

    func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
        reachfive.application(application, continue: userActivity, restorationHandler: restorationHandler) <3>
    }

    func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
        reachfive.application(app, open: url, options: options) <4>
    }

    func applicationDidBecomeActive(_ application: UIApplication) {
        reachfive.applicationDidBecomeActive(application) <5>
    }
}
----
<1> An example of how to access the {company} object from within the app.
<2> Initializes the iOS SDK by fetching information from the server about the client.
For more details, see xref:application/applicationDidFinishLaunchingWithOptions.adoc[].
<3> This method is used to handle universal links which are used by providers.
For more details, see xref:application/applicationContinueUserActivity.adoc[].
<4> This method is used to handle callback schemes which are used by passwordless, MFA and account recovery, as well as providers.
For more details, see xref:application/applicationOpenUrl.adoc[].
<5> This method is used to provide functionality to the providers.
For more details, see xref:application/applicationDidBecomeActive.adoc[].

--
====
